name: SP_Shop
version: '1.0-SNAPSHOT'
main: fr.silvercore.sP_Shop.SP_Shop
api-version: '1.18'
prefix : SilverPlugins
load: STARTUP
authors: [ Silvercore, JemY5, Silverdium ]
website: core.silverdium.fr
